//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyModels.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public string FilePath { get; set; }
        public int TypeId { get; set; }
        public long FileId { get; set; }
        public Nullable<long> AdvertisementId { get; set; }
    
        public virtual Advertisement Advertisement { get; set; }
        public virtual Type Type { get; set; }
    }
}
