//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisingCampaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvertisingCampaign()
        {
            this.Accounts = new HashSet<Account>();
            this.Advertisements = new HashSet<Advertisement>();
        }
    
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string CampaignName { get; set; }
        public string Slogan { get; set; }
        public string Characteristic { get; set; }
        public long AgencyId { get; set; }
        public long CampaignId { get; set; }
        public long ClientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisement> Advertisements { get; set; }
        public virtual Agency Agency { get; set; }
        public virtual Client Client { get; set; }
    }
}
